---
title: "1.4.3 競合学習"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

手書き文字(digit)認識をします。データは下記からダウンロードしてください。  
http://www.kaggle.com/c/digit-recognizer

```{r}
setwd("C:/Users/k-harada/Desktop/kdd/digit/ORG")
library(data.table)
library(dplyr)
traindata <- fread("train.csv")
testdata <- fread("test.csv")

train_label <- traindata$label[1:28000]
valid_label <- traindata$label[28001:42000]

# do not resize here
# /255 so that range in 0-1
train_mat <- as.matrix(traindata[1:28000, ])[, -1]/255
valid_mat <- as.matrix(traindata[28001:42000, ])[,-1]/255
```


## 簡単な競合学習
出力層を25個として競合学習します

#### 初期値の設定
```{r}
set.seed(0)
W <- matrix(rnorm(100*28*28), nrow=100)
# 規格化
for (i in seq(100)){
  W[i, ] <- W[i, ] / sqrt(sum(W[i, ]*W[i, ]))
}
# 表示
imagemat <- matrix(0, nrow=28*10, ncol=28*10)
for (i in seq(100)){
  imagemat[floor((i-1)/10)*28+1:28,((i-1)%%10)*28+1:28] <- matrix(W[i, ], ncol=28)
}
image(imagemat, ylim=c(1,0))
```

#### 学習(教師なし)
完全ランダムだとうまくいかないので、近隣も学習するようにする
(コホネンネットワーク)

```{r}
eta <- 0.01

for (i in seq(28000)){
  x <- train_mat[i, ]
  # 規格化
  x <- x / sqrt(sum(x*x))
  # 最大出力をみつける
  xtes <- which.max(W %*% x)
  for (j in seq(100)){
    dj <- (((xtes-1)%%10) - ((j-1)%%10)) ** 2 + (floor((xtes-1)/10) - floor((j-1)/10)) ** 2
    # UPDATE
    W[j, ] <- W[j, ] + eta*x / (1+dj)
    # 規格化
    W[j, ] <- W[j, ] / sqrt(sum(W[j, ]*W[j, ]))
  }
}
# 表示
imagemat <- matrix(0, nrow=28*10, ncol=28*10)
for (i in seq(100)){
  imagemat[floor((i-1)/10)*28+1:28,((i-1)%%10)*28+1:28] <- matrix(W[i, ], ncol=28)
}
image(imagemat, ylim=c(1,0))
```

